version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/flowers_works_deploy
hooks:
  BeforeInstall:
    - location: scripts/prepare_deploy.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
    - location: scripts/sync_files.sh
      timeout: 300
      runas: root
    - location: scripts/create_application_files.sh
      timeout: 300
      runas: root
